### ISSUE TITLE
Add mapping of `keys.*.configmap_key` to `keys.*.config_service_key`

### ISSUE THREAD

**Issue by OlegGorj** [OlegGorj/config-data-operator#4]
theme: presently operator uses `keys.*.config_service_key` to generate ConfigMap configuration names, it also uses the same key to create ConfigMap key. 

_Example_

configmaps.json:

```
[
	
	{
		"namespace": "default",
		"configmap": "cassandra-test",
		"config": "cassandra.json",
		"keys": [
			{
				"configmap_key": "application",
				"config_service_key": "app"
			},
			{
				"configmap_key": "services",
				"config_service_key": "cassandra_services"
			}
		]
	}
]
```

After the operator generates ConfigMap, it looks like:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-test
  maintained_by: config_operator
  namespace: cassandra-namespace
data:
  app: cassandra
  cassandra_services: ["cassandra.dc1" , "cassandra.dc2"]
```

Desired outcome should use the key `keys.*.configmap_key` to generate ConfigMap configuration names, as such:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-test
  maintained_by: config_operator
  namespace: cassandra-namespace
data:
  application: cassandra
  services: ["cassandra.dc1" , "cassandra.dc2"]
```
